In [2]:
import sys
sys.executable

'/usr/local/opt/python@3.11/bin/python3.11'

In [3]:
import ast
import pandas as pd
import numpy as np
from pygit2 import Object, Repository, GIT_SORT_TIME
from pygit2 import init_repository, Patch
from colorama import Fore
from tqdm import tqdm
import swifter
from pandarallel import pandarallel

In [4]:
pandarallel.initialize(progress_bar=True)

INFO: Pandarallel will run on 8 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

In [5]:
library = 'lablup/backend.ai'

In [6]:
# import all push data
df_push = pd.DataFrame()
commit_urls = []
for val in np.arange(0, 100, 1):
    if val < 10:
        val = "0" + str(val)
    try:
        df_part = pd.read_csv(f'data/github_clean/pushEvent0000000000{val}.csv', index_col = 0)
        df_part['partition'] = val
        df_push = pd.concat([df_push, df_part])
    except:
        print(f'data/github_clean/pushEvent0000000000{val}.csv not found')

In [7]:
df_library = df_push[df_push['repo_name'] == library]
df_library.loc[:,'commit_urls'] = df_library['commit_urls'].apply(lambda x: ast.literal_eval(x))
commit_urls = df_library['commit_urls'].explode().tolist()

In [10]:
commit_urls

['https://api.github.com/repos/lablup/backend.ai/commits/c86f4dfeff22249776420ae09f05b4bb42a1cc17',
 'https://api.github.com/repos/lablup/backend.ai/commits/bede3c289c0a2b3620d07e061d986f52898654d9',
 'https://api.github.com/repos/lablup/backend.ai/commits/1d3fb81cd14a6ad29076d5b68bf023da8d6ee9db',
 'https://api.github.com/repos/lablup/backend.ai/commits/65825b700f625d28b0aa2007de74c2525aaeac47',
 'https://api.github.com/repos/lablup/backend.ai/commits/e6bafb07336e62c6348f69ffc50e04400c6f1ad1',
 'https://api.github.com/repos/lablup/backend.ai/commits/721bed41b4b49666e27ec8d98c4df1e6c9d6d1b9',
 'https://api.github.com/repos/lablup/backend.ai/commits/fac985115603436d8e86a2e9833683f718565be7',
 'https://api.github.com/repos/lablup/backend.ai/commits/bca7f0302562ac70c36ad4fe358e1066450d47bc',
 'https://api.github.com/repos/lablup/backend.ai/commits/a04289219a866223fdd853d825f4dba586e5476b',
 'https://api.github.com/repos/lablup/backend.ai/commits/65547bb7f9e5522d9f2b8933ce1d1c05126453e0',
 'https://api.github.com/repos/lablup/backend.ai/commits/d7cf4db01f7870d6fc2835f66c8565c2bde21cb7',
 'https://api.github.com/repos/lablup/backend.ai/commits/3307f471f8d9d2b9315b83266d8c41f51556efd7',
 'https://api.github.com/repos/lablup/backend.ai/commits/e31a358c3041e7b500aa8b8d9ebc21c338c32aaf',
 'https://api.github.com/repos/lablup/backend.ai/commits/3f9bebf2121d5addcd541ac51523b0e28b9c88b0',
 'https://api.github.com/repos/lablup/backend.ai/commits/4cc3ee4cfc331f04bc447176dd12981794499b92',
 'https://api.github.com/repos/lablup/backend.ai/commits/055b7b544ea54150a8ce81368aa8c7dd4d13b943',
 'https://api.github.com/repos/lablup/backend.ai/commits/f405487863135b66c635a5200b52df4712285b06',
 'https://api.github.com/repos/lablup/backend.ai/commits/b8180606b17dd16724a7e5e97b863dd7e8a76243',
 'https://api.github.com/repos/lablup/backend.ai/commits/b746e1d9e643899fb49bf03ed1c56b1aea0479b4',
 'https://api.github.com/repos/lablup/backend.ai/commits/08295e25c0196b1f56ea8c1a207fc4e0454fef9c',
 'https://api.github.com/repos/lablup/backend.ai/commits/e7bbbadadb5a6823e21ec354134400985801132f',
 'https://api.github.com/repos/lablup/backend.ai/commits/af24c0d26e97f2dc963211953e55a48fc0837a37',
 'https://api.github.com/repos/lablup/backend.ai/commits/d6422452d1869bd2d65645abf6b8baa7f5b6eadc',
 'https://api.github.com/repos/lablup/backend.ai/commits/9dd5cfff446519441596376c3cd172e6cee673dc',
 'https://api.github.com/repos/lablup/backend.ai/commits/a5f8fd27f87d3657101e004660a91fdb573dc837',
 'https://api.github.com/repos/lablup/backend.ai/commits/270579b6941e10a0426950b40f3078d6918df32d',
 'https://api.github.com/repos/lablup/backend.ai/commits/98f2f84de01e0bfd4d30b64642881617f45e6c34',
 'https://api.github.com/repos/lablup/backend.ai/commits/eeaec87100c044f94b6c6f648a9ffb03b8994838',
 'https://api.github.com/repos/lablup/backend.ai/commits/10ff4c680f1beb0a02b42b2d582977e9f11f28e1',
 'https://api.github.com/repos/lablup/backend.ai/commits/f043db4c39c3f6ff64aa78da22b32bb81838b661',
 'https://api.github.com/repos/lablup/backend.ai/commits/eb83472a548591acca2ab9309806c2cf0e9a698f',
 'https://api.github.com/repos/lablup/backend.ai/commits/76189ab8b2f40f42aca13fe58f1774e394fb110c',
 'https://api.github.com/repos/lablup/backend.ai/commits/b4313af27e3c466203463cccd2b23a25370c8ad3',
 'https://api.github.com/repos/lablup/backend.ai/commits/cf64680b067486f3b1743731f756254d9202bb71',
 'https://api.github.com/repos/lablup/backend.ai/commits/16f92b0ce05ac71651de2b48826741fb471ed3a7',
 'https://api.github.com/repos/lablup/backend.ai/commits/dc1f3eb77f195c4f79356def5ccec468daafaf7c',
 'https://api.github.com/repos/lablup/backend.ai/commits/c4ccbc1412ae61df6cc9391e585eba215f20a78d',
 'https://api.github.com/repos/lablup/backend.ai/commits/629fb5b436721c142fdcd869483e1cb3abc3ab2b',
 'https://api.github.com/repos/lablup/backend.ai/commits/15253b9e34b09418f616378bdf31af60b63ad93b',
 'https://api.github.com/repos/lablup/backend.ai/commits/9e2b130962c74372234283f6b3c2116fce762c06',
 'https://api.github.com/repos/lablup/backend.ai/commits/781b91573a08b9b2096bd3c4703d6f36389d2d14',
 'https://api.github.com/repos/lablup/backend.ai/commits/eb3fd162dbfc3dcf9f81173ec426eed7ca2e6267',
 'https://api.github.com/repos/lablup/backend.ai/commits/af5d2d499580aa6b17b9a60606c35d4b63aa6c25',
 'https://api.github.com/repos/lablup/backend.ai/commits/9ea3b09e60924065deae644068c36b507c9a2a45',
 'https://api.github.com/repos/lablup/backend.ai/commits/45d92dbf9cab31dcf8a00506dd458378cb9457ae',
 'https://api.github.com/repos/lablup/backend.ai/commits/bc9c8657cf75e30ce8819595b176cfdb07bba6cc',
 'https://api.github.com/repos/lablup/backend.ai/commits/0c505e32b183ef23baa7785f515083d1aad2c36b',
 'https://api.github.com/repos/lablup/backend.ai/commits/5601749fe7c8c3130ca94a7c4435447d7f074644',
 'https://api.github.com/repos/lablup/backend.ai/commits/faf51b424afe8109484645ef2ecd96af369f4e0a',
 'https://api.github.com/repos/lablup/backend.ai/commits/df590977f7e7b46915ad6d07632d54d2d073e391',
 'https://api.github.com/repos/lablup/backend.ai/commits/a62d36504a144b0279ea3c51370dc977f398395b',
 'https://api.github.com/repos/lablup/backend.ai/commits/4451b04ca56fc586e5f7b16bdb7d9d37378516b8',
 'https://api.github.com/repos/lablup/backend.ai/commits/ff15804908327ea36997f85470da3fcddef07554',
 'https://api.github.com/repos/lablup/backend.ai/commits/832427d363685ff8197c2ab94ab4a91f6c81a648',
 'https://api.github.com/repos/lablup/backend.ai/commits/ed87e31bfd9811e1b29b67c2547918dbe4530a69',
 'https://api.github.com/repos/lablup/backend.ai/commits/d9ff21af430fc12ce210da703bc5c9a3e8feea60',
 'https://api.github.com/repos/lablup/backend.ai/commits/35976e6f99b522b744eb5ab04204f8432ced1663',
 'https://api.github.com/repos/lablup/backend.ai/commits/51a93078349b53a7da188087c3e3c16d84de84e7',
 'https://api.github.com/repos/lablup/backend.ai/commits/ef4156a0a5cdb4ee1aec181a9675c24d92cf9517',
 'https://api.github.com/repos/lablup/backend.ai/commits/5bedf18db411191e45f1cb612b0bedda7f1df608',
 'https://api.github.com/repos/lablup/backend.ai/commits/2d4b5114ed4142f0cf3c7acf1fe6d6e3038749c4',
 'https://api.github.com/repos/lablup/backend.ai/commits/5b7ec6c464a1031068f9652dda7a0fa2ac3bfbf6',
 'https://api.github.com/repos/lablup/backend.ai/commits/0bbf34d22e726d84c15b9eb44290c79434dc4f4a',
 'https://api.github.com/repos/lablup/backend.ai/commits/8d1f41b434e6470d7dfcbb4b5936f868f14382ad',
 'https://api.github.com/repos/lablup/backend.ai/commits/ca221d6cc64eee6aa19be661613d6e5467e0ca15',
 'https://api.github.com/repos/lablup/backend.ai/commits/833487ca2bcf346999aad8c30838710f69ac4686',
 'https://api.github.com/repos/lablup/backend.ai/commits/9f9ecfada361bdc5a8cd46bd83cd564942f91b18',
 'https://api.github.com/repos/lablup/backend.ai/commits/1cb54e10d96af3d5e93a9227f7833229dcd274a9',
 'https://api.github.com/repos/lablup/backend.ai/commits/7c2a640f5e83546f7af9ee53d49f34940942bb1b',
 'https://api.github.com/repos/lablup/backend.ai/commits/a2b1ce86bf0447e503547541ab09efe311de49a5',
 'https://api.github.com/repos/lablup/backend.ai/commits/d38ba043cd9509c66046517b4da0b1bb8cca706e',
 'https://api.github.com/repos/lablup/backend.ai/commits/44e2e3fa12e1c0e5ed943264495e6451c821430a',
 'https://api.github.com/repos/lablup/backend.ai/commits/5435602c98b153d0e4b9f55196a7e4be89de088e',
 'https://api.github.com/repos/lablup/backend.ai/commits/e88d11b6834a2c369d01700b5990737679e056e1',
 'https://api.github.com/repos/lablup/backend.ai/commits/237f9f7026a908283d9bbc35dc4aff3aca8888b4',
 'https://api.github.com/repos/lablup/backend.ai/commits/d7e830579a0af7dd736511ed3714066c84465d15',
 'https://api.github.com/repos/lablup/backend.ai/commits/58c9a06ed9902940acbb19fe2eb679c37d8033c7',
 'https://api.github.com/repos/lablup/backend.ai/commits/7d26fba3b3060cc7eabd7618f6c9968a8c41a1f9',
 'https://api.github.com/repos/lablup/backend.ai/commits/5e0b6632f3f6597abc3a9810c7fd0753a144e1de',
 'https://api.github.com/repos/lablup/backend.ai/commits/44095a1a9f425bd69287b2987b6e734a6666687d',
 'https://api.github.com/repos/lablup/backend.ai/commits/c32b2e25326267d1ae8a8724dd8df7b4845dcaa8',
 'https://api.github.com/repos/lablup/backend.ai/commits/e8329478bd2ec499db859cb87826d2094f8fa9f0',
 'https://api.github.com/repos/lablup/backend.ai/commits/b0e37638213bcaf3eb8fbb7a3632da75a62665c7',
 'https://api.github.com/repos/lablup/backend.ai/commits/e27a7900fe25a6e392a3ff35da593d071422d65b',
 'https://api.github.com/repos/lablup/backend.ai/commits/ffed4e0400962d7f88823077a9d0ee5b465085b8',
 'https://api.github.com/repos/lablup/backend.ai/commits/dc101c0fd606c6991a468d453af47c4e0395737b',
 'https://api.github.com/repos/lablup/backend.ai/commits/f3853c497b08b1c35f5974e80d4ed0c2a10aa53c',
 'https://api.github.com/repos/lablup/backend.ai/commits/c211850965543a32f5a42c7a9cc8c5a916f55058',
 'https://api.github.com/repos/lablup/backend.ai/commits/be53e1b826ad6fae609e6b3f1ffd9c64160a25bf',
 'https://api.github.com/repos/lablup/backend.ai/commits/4c8c99194867df47911a762b2a59e32519976705',
 'https://api.github.com/repos/lablup/backend.ai/commits/f24a0bb3c981d1600ef3a66c59787e9e3ffc5ef7',
 'https://api.github.com/repos/lablup/backend.ai/commits/512aa6006a08b9782c26790884df4d6d879c8eb5',
 'https://api.github.com/repos/lablup/backend.ai/commits/61a4cba5627839e4a2d50a8ed5f657f1eda0a30f',
 'https://api.github.com/repos/lablup/backend.ai/commits/837857d7f73b8b3d4d67ba9105690baf2add33d1',
 'https://api.github.com/repos/lablup/backend.ai/commits/61d2d7071ce3d6a4016ed8391178f1993e0e9368',
 'https://api.github.com/repos/lablup/backend.ai/commits/154270798fd807011340eca12d13caa39df69217',
 'https://api.github.com/repos/lablup/backend.ai/commits/05ce1fc4d4c0a22728d9d31c9de499c1f87e3866',
 'https://api.github.com/repos/lablup/backend.ai/commits/b6cab7476f09a7654432dcf901bb172c68e73d40',
 'https://api.github.com/repos/lablup/backend.ai/commits/9d9417ec4115d2a3490a07e1c5bc03a43d41b1a2',
 'https://api.github.com/repos/lablup/backend.ai/commits/036fa7313097cd89b059dcc141f920642b970fd9',
 'https://api.github.com/repos/lablup/backend.ai/commits/9619aacdc9f7e38fb1d236d4cca02870290a53ca',
 'https://api.github.com/repos/lablup/backend.ai/commits/a4d10feb69c080a6c70b59422e0d584fb9250e73',
 'https://api.github.com/repos/lablup/backend.ai/commits/fa0695adbb6a65355a83f85428fb367b6baf6802',
 'https://api.github.com/repos/lablup/backend.ai/commits/380887bcd061201eafe27f95f3e8ef09d106026a',
 'https://api.github.com/repos/lablup/backend.ai/commits/b631a4a4feccbf2f0afd5e413d5367e68dfb1a26',
 'https://api.github.com/repos/lablup/backend.ai/commits/0b9ad0d1d481886812d6417e7b617b2be87f0ced',
 'https://api.github.com/repos/lablup/backend.ai/commits/a0701960459af5d8f66d6fac8ad648d8f67e436b',
 'https://api.github.com/repos/lablup/backend.ai/commits/09f7967ee7e02390fdd3552154243c0008811c9a',
 'https://api.github.com/repos/lablup/backend.ai/commits/70a90628fbe426b00df11d8ef5e51ac02a995fea',
 'https://api.github.com/repos/lablup/backend.ai/commits/93eaf05d779a4f584a5be297af7cd99cecc7a607',
 'https://api.github.com/repos/lablup/backend.ai/commits/e4983d428fa485798015eb3950e4701c3e4c89c8',
 'https://api.github.com/repos/lablup/backend.ai/commits/750802578ea34f30500ebb169137afb64f93b0aa',
 'https://api.github.com/repos/lablup/backend.ai/commits/b0ce47e16ea811f8723cb638730858851138d7b0',
 'https://api.github.com/repos/lablup/backend.ai/commits/ece31f574e563c7b424ab226dec01afec176bb87',
 'https://api.github.com/repos/lablup/backend.ai/commits/8b9eda2cc74f9a8ed26bd3485e5a262c02d63b80',
 'https://api.github.com/repos/lablup/backend.ai/commits/75140140bd859549d74f7c0e30530e6b699e728c',
 'https://api.github.com/repos/lablup/backend.ai/commits/9cb29046f5b3189be4ac25029f45feb7ddec2591',
 'https://api.github.com/repos/lablup/backend.ai/commits/2decacc70ccbc63d5830c5f7a1907e0e1b8add1d',
 'https://api.github.com/repos/lablup/backend.ai/commits/2be90a2e02c690d67e2445d3abede4a297bbbbe4',
 'https://api.github.com/repos/lablup/backend.ai/commits/8a5e8324fa9d7049e00248c17ca2b190408ce121',
 'https://api.github.com/repos/lablup/backend.ai/commits/7f92d2ece36a8edd3559bef70d0ec3f45fbdd601',
 'https://api.github.com/repos/lablup/backend.ai/commits/57ad1df631051df8f9c48bd2810797d7cf0566df',
 'https://api.github.com/repos/lablup/backend.ai/commits/b8e48c0851e3e9e32fdfc0db8eecce31cb5439ea',
 'https://api.github.com/repos/lablup/backend.ai/commits/6209cd1ddc2d6090d88ad799d8b571a2d4cafac5',
 'https://api.github.com/repos/lablup/backend.ai/commits/59622bdb036db0d035ffa4b130f3e541dfc94f98',
 'https://api.github.com/repos/lablup/backend.ai/commits/8be780b530fb0c5b268ea00df67a74cac8200284',
 'https://api.github.com/repos/lablup/backend.ai/commits/20d878b5c4f2eadb538eeef4f577a011f7fb5887',
 'https://api.github.com/repos/lablup/backend.ai/commits/c666327407e85fc27dc5dabd6cf2e426b318af3d',
 'https://api.github.com/repos/lablup/backend.ai/commits/f2ebf3d4e8277618731f8c01e967ef1de283d087',
 'https://api.github.com/repos/lablup/backend.ai/commits/395ea3b7d946e743422a630b71c413707cb786d9',
 'https://api.github.com/repos/lablup/backend.ai/commits/39f77f528718bc57454dce825b5688880b203a5e',
 'https://api.github.com/repos/lablup/backend.ai/commits/9604d3c9a12970745df5c558d9c05064a4541eb2',
 'https://api.github.com/repos/lablup/backend.ai/commits/9ae6fbbccda0e7c595ec99c280d5acaa16373ec9',
 'https://api.github.com/repos/lablup/backend.ai/commits/360b235928c2e4cc8d711cbf5fd8046d35a35f29',
 'https://api.github.com/repos/lablup/backend.ai/commits/947c955e7cff655386d0aebd7a120a1469a69a1b',
 'https://api.github.com/repos/lablup/backend.ai/commits/fce8c2f909e75f5598f06c9abc29a42cd19b1eb6',
 'https://api.github.com/repos/lablup/backend.ai/commits/809edca200bba722a86a9ff611c0fed2f6bbc8c7',
 'https://api.github.com/repos/lablup/backend.ai/commits/984ae7adfc5f8662f546b001c03720e26fb8dece',
 'https://api.github.com/repos/lablup/backend.ai/commits/db9f8cd15ed25b394d553c39c5c3b83730b50d1e',
 'https://api.github.com/repos/lablup/backend.ai/commits/0b71304bbf6f83d456a8adeb11022fbdf1a60e75',
 'https://api.github.com/repos/lablup/backend.ai/commits/77c89bd6c0ebe1c117ce535bb6279efee67b15e8',
 'https://api.github.com/repos/lablup/backend.ai/commits/1b91e306dd061975e9e917f76466bc0c71be7043',
 'https://api.github.com/repos/lablup/backend.ai/commits/63ea1b885ed06534c6098c27881677fb3b0909c2',
 'https://api.github.com/repos/lablup/backend.ai/commits/f136270815711b236e7205cd59e35ebc954a7bd2',
 'https://api.github.com/repos/lablup/backend.ai/commits/883895700702e53cc38d02f55f8b4e10244daed3',
 'https://api.github.com/repos/lablup/backend.ai/commits/94aacb5ece8b04a1a6f803e580a102772d387a91',
 'https://api.github.com/repos/lablup/backend.ai/commits/9d3e22657ff6541ad65b36de7d267313af8b55ea',
 'https://api.github.com/repos/lablup/backend.ai/commits/19c4892c4a61eeae423f62725fe873dcc1af0f2b',
 'https://api.github.com/repos/lablup/backend.ai/commits/dd78355fd096804bad5d21715358be4fe11f1055',
 'https://api.github.com/repos/lablup/backend.ai/commits/4fe1caf4d9205771cc5d4f9135be5779cd88d6f2',
 'https://api.github.com/repos/lablup/backend.ai/commits/692c7689806150b2ffdb598cebd72db06d232553',
 'https://api.github.com/repos/lablup/backend.ai/commits/f74e2f16d160f779295c8c13b753e2a0ff78d3b0',
 'https://api.github.com/repos/lablup/backend.ai/commits/c7906cf6be9bb60fb208625b857596f02573b492',
 'https://api.github.com/repos/lablup/backend.ai/commits/72585dccbea3daccc8e8637af8b86290605d9d6f',
 'https://api.github.com/repos/lablup/backend.ai/commits/969fb296c64d915975e6dbafb4f317d1bb11459a',
 'https://api.github.com/repos/lablup/backend.ai/commits/1e0dd464306969bc71a80331da8c3de79a352c96',
 'https://api.github.com/repos/lablup/backend.ai/commits/f280a66e04372d11bac8d823dd99d1621ba56648',
 'https://api.github.com/repos/lablup/backend.ai/commits/f244d47a66c465409d6e6149e240536ccd0b96bf',
 'https://api.github.com/repos/lablup/backend.ai/commits/f10a78b5ad596e5d8ef6bbba76d52083fedc817b',
 'https://api.github.com/repos/lablup/backend.ai/commits/0cb109e44a30b1f9b6653ae74e6c6451f7acf78f',
 'https://api.github.com/repos/lablup/backend.ai/commits/15291d244bdda2a15f374b7d79e9f2b84ecc9bb3',
 'https://api.github.com/repos/lablup/backend.ai/commits/e1540d71dbda0072a2ad99a31fc1413e69bfc22f',
 'https://api.github.com/repos/lablup/backend.ai/commits/4438cc12ac5e2a880736cc26cc271ab5ccb4a7a5',
 'https://api.github.com/repos/lablup/backend.ai/commits/385eb662b259edd8cc25c92ca83d8bec87e9078b',
 'https://api.github.com/repos/lablup/backend.ai/commits/7fec592a8de4aebb1711257bc4dbbbe9c2d3b5c2',
 'https://api.github.com/repos/lablup/backend.ai/commits/b17ed8ac5d1651dfb5129df4cea5aa7b0d827746',
 'https://api.github.com/repos/lablup/backend.ai/commits/6c10da63fd0e16c3593f58f13705363c859d764a',
 'https://api.github.com/repos/lablup/backend.ai/commits/c6da3e6d4599abb5ea9149a15dabafe31e8f8970',
 'https://api.github.com/repos/lablup/backend.ai/commits/3cd424bb37fdcdcae2af28a856b3ed3d0b2515a6',
 'https://api.github.com/repos/lablup/backend.ai/commits/1884b19400c245aecdcf804001fec9571a819e9f',
 'https://api.github.com/repos/lablup/backend.ai/commits/44a39c5cb83367438120314b43cc2c15285e76f5',
 'https://api.github.com/repos/lablup/backend.ai/commits/9d91886b4b9e07ef0370036b31c76182561952cf',
 'https://api.github.com/repos/lablup/backend.ai/commits/3e21ca2cc7f6e0298b36b41ba0fd4a00ef1ebfea',
 'https://api.github.com/repos/lablup/backend.ai/commits/c0468a98685494ef0e107fcdb12ebf968e8f8e8d',
 'https://api.github.com/repos/lablup/backend.ai/commits/be8dcbd34a4e0935e353da0b704c9ca4625bc824',
 'https://api.github.com/repos/lablup/backend.ai/commits/324a555b14700348a69d0825bd1c87f1f4057eda',
 'https://api.github.com/repos/lablup/backend.ai/commits/9f20da4f6d576946737c6b49705d3c493afc55e1',
 'https://api.github.com/repos/lablup/backend.ai/commits/92e2d1c62b3567737ddfe6505c92479e6edcbd58',
 'https://api.github.com/repos/lablup/backend.ai/commits/8bb8a9a0ded7dfdd7ac3cdb66c9b978ef4793f1e',
 'https://api.github.com/repos/lablup/backend.ai/commits/f48a16115644a64dc46239d258a17460bfe23f64',
 'https://api.github.com/repos/lablup/backend.ai/commits/2f71734edfe7b847867d9a3db32dbd18e8595900',
 'https://api.github.com/repos/lablup/backend.ai/commits/76b3af51359b3c6b821f9dd9568a4ee8de3219e8',
 'https://api.github.com/repos/lablup/backend.ai/commits/46dc799920a2f3d6b78af4924342eb1aba400bfe',
 'https://api.github.com/repos/lablup/backend.ai/commits/28ceec6a900153d61e4302b78364fff3baa50e09',
 'https://api.github.com/repos/lablup/backend.ai/commits/dd6c502e2d27c9ff9224efdad4aaee6589b32608',
 'https://api.github.com/repos/lablup/backend.ai/commits/a6b5ac84097691c4cfeec5c847aef8aa2e2bf010',
 'https://api.github.com/repos/lablup/backend.ai/commits/c45b1550c0e9bb8cdac87ba5f7c87d1ea15b0902',
 'https://api.github.com/repos/lablup/backend.ai/commits/f884d1b4b3820de622b118035fafa24a1dc44ea5',
 'https://api.github.com/repos/lablup/backend.ai/commits/bbdcc7b52c03dc734b2086fdd25b73dc4ceac985',
 'https://api.github.com/repos/lablup/backend.ai/commits/ebda92fb481c1976c1efb0175275acb709e1e4a8',
 'https://api.github.com/repos/lablup/backend.ai/commits/3a2801bc7ca50e6cf40857cde7a7e553409620e2',
 'https://api.github.com/repos/lablup/backend.ai/commits/09ab5bd43d5de580f7721458197aa5213d19dd71',
 'https://api.github.com/repos/lablup/backend.ai/commits/ab24f7594154a1bd7fd93ccf571695ddcb4b811b',
 'https://api.github.com/repos/lablup/backend.ai/commits/ef36ce0930b8f1942a79d6463e1bdfd7b4a497af',
 'https://api.github.com/repos/lablup/backend.ai/commits/633cd55ba9200961e29def4ede0d44cefed63ec1',
 'https://api.github.com/repos/lablup/backend.ai/commits/372a34cbc407638479eb74d8a5f3601284cf1cf9',
 'https://api.github.com/repos/lablup/backend.ai/commits/2d222f3226b0392c435959d07068a9e30b0a7dbd',
 'https://api.github.com/repos/lablup/backend.ai/commits/3b015f3ff235025aab3bb62e1cff56bb2d2d678a',
 'https://api.github.com/repos/lablup/backend.ai/commits/8c2632f0bdc5ee6d1a9f366ad642190f21f2ed4f',
 'https://api.github.com/repos/lablup/backend.ai/commits/54473171ced42d3d0ffbc3aff508d34f2640e5e6',

In [387]:
repo = Repository('../repos/backend.ai')
sum = 0
for commit in commit_urls:
    if type(commit) != float:
        sha = commit.split("/")[-1]
        commit_a = repo.get(sha)
        if type(commit_a) != type(None):
            sum += 1
print(f"{sum} out of {len(commit_urls)} commit SHAs can be found ({100*round(sum/len(commit_urls), 3)}%)")

21523 out of 25698 commit SHAs can be found (83.8%)

In [388]:
def createCommitGroup(push_before, push_head, commit_urls, push_size):
    if push_size == 0:
        return [[]]
    elif push_size == 1:
        return [[push_before, push_head]]
    else:
        avail_commits = len(commit_urls)
        lst_result = [[push_before, commit_urls[0].split("/")[-1]]]
        for i in range(avail_commits-1):
            lst_result.append([commit_urls[i].split("/")[-1], commit_urls[i+1].split("/")[-1]])
        return lst_result

In [389]:
df_library['commit_groups'] = \
    df_library.apply(lambda x: createCommitGroup(x['push_before'], x['push_head'], x['commit_urls'], x['push_size']), axis = 1)
df_commit_groups = df_library[['push_id', 'repo_id', 'repo_name', 'actor_id', 'actor_login', 
                               'org_id', 'org_login', 'push_size', 'push_before', 'push_head',
                               'commit_groups']].explode('commit_groups')

/var/folders/5s/dvrxt95949x1pm_sjxm85lj00000gn/T/ipykernel_39288/1534266405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_library['commit_groups'] = \

In [390]:
def returnCommitStats(x):
    if len(x) < 2:
        return []
    commit_parent_sha = x[0]
    commit_head_sha = x[1]
    commit_parent = repo.get(commit_parent_sha)
    commit_head = repo.get(commit_head_sha)
    if type(commit_parent) != type(None) and type(commit_head) != type(None):
        diff = repo.diff(commit_parent, commit_head, context_lines=0, interhunk_lines=0)
        commit_sha = commit_head_sha
        commit_author_name = commit_head.author.name
        commit_author_email = commit_head.author.email
        committer_author_name = commit_head.committer.name
        committer_author_email = commit_head.committer.email
        commit_message = commit_head.message
        commit_additions = diff.stats.insertions
        commit_deletions = diff.stats.deletions
        commit_changes_total = commit_additions + commit_deletions
        commit_files_changed_count = diff.stats.files_changed
        commit_time = commit_head.commit_time
        commit_file_changes = []
        
        for obj in diff:
            if type(obj) == Patch:
                additions = 0
                deletions = 0
                for hunk in obj.hunks:
                  for line in hunk.lines:
                    # The new_lineno represents the new location of the line after the patch. If it's -1, the line has been deleted.
                    if line.new_lineno == -1: 
                        deletions += 1
                    # Similarly, if a line did not previously have a place in the file, it's been added fresh. 
                    if line.old_lineno == -1: 
                        additions += 1
                commit_file_changes.append({'file':obj.delta.new_file.path,
                                            'additions': additions,
                                            'deletions': deletions,
                                            'total': additions + deletions})
        return [commit_sha, commit_author_name, commit_author_email, committer_author_name, committer_author_email,
                commit_message, commit_additions, commit_deletions, commit_changes_total, commit_files_changed_count,
                commit_file_changes]
    return []

In [392]:
%%time
commit_data = df_commit_groups['commit_groups'].parallel_apply(returnCommitStats)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=3213), Label(value='0 / 3213'))), …

CPU times: user 1.54 s, sys: 1.02 s, total: 2.56 s
Wall time: 12min 53s

In [393]:
df_commit = pd.DataFrame(commit_data.tolist(),
                        columns = ['commit sha', 'commit author name', 'commit author email', 'committer name',
                                   'commmitter email', 'commit message', 'commit additions', 'commit deletions',
                                   'commit changes total', 'commit files changed count', 'commit file changes'])

In [394]:
df_commit_final = pd.concat([df_commit_groups.reset_index(drop = True), df_commit], axis = 1)
df_commit_final

,push_id,repo_id,repo_name,actor_id,actor_login,org_id,org_login,push_size,push_before,push_head,...,commit author name,commit author email,committer name,commmitter email,commit message,commit additions,commit deletions,commit changes total,commit files changed count,commit file changes
0,11550771535,70124554,lablup/backend.ai,2904494,kyujin-cho,11258248.0,lablup,84,f7288e25e5ba7e30ed58946942ea52413912d0bd,e27a7900fe25a6e392a3ff35da593d071422d65b,...,None,None,None,None,None,NaN,NaN,NaN,NaN,None
1,11550771535,70124554,lablup/backend.ai,2904494,kyujin-cho,11258248.0,lablup,84,f7288e25e5ba7e30ed58946942ea52413912d0bd,e27a7900fe25a6e392a3ff35da593d071422d65b,...,Joongi Kim,joongi@lablup.com,GitHub,noreply@github.com,setup: Remove dependency to psycopg (#702)\n\n...,204.0,296.0,500.0,21.0,"[{'file': 'changes/702.breaking.md', 'addition..."
2,11550771535,70124554,lablup/backend.ai,2904494,kyujin-cho,11258248.0,lablup,84,f7288e25e5ba7e30ed58946942ea52413912d0bd,e27a7900fe25a6e392a3ff35da593d071422d65b,...,Sanghun Lee,oper6909@gmail.com,GitHub,noreply@github.com,feat: Do not return AgentSummary if `hide-agen...,10.0,2.0,12.0,2.0,"[{'file': 'changes/699.feature.md', 'additions..."
3,11550771535,70124554,lablup/backend.ai,2904494,kyujin-cho,11258248.0,lablup,84,f7288e25e5ba7e30ed58946942ea52413912d0bd,e27a7900fe25a6e392a3ff35da593d071422d65b,...,Jonghyun Park,jpark@lablup.com,GitHub,noreply@github.com,feat: add `hide_agents` webserver config (#704...,6.0,1.0,7.0,4.0,"[{'file': 'changes/704.feature', 'additions': ..."
4,11550771535,70124554,lablup/backend.ai,2904494,kyujin-cho,11258248.0,lablup,84,f7288e25e5ba7e30ed58946942ea52413912d0bd,e27a7900fe25a6e392a3ff35da593d071422d65b,...,DaeHyun Sung,dhsung@lablup.com,GitHub,noreply@github.com,docs: update python default version (#724)\n\n...,1448.0,996.0,2444.0,11.0,"[{'file': 'docs/README.md', 'additions': 1, 'd..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25693,11646000079,70124554,lablup/backend.ai,555156,achimnol,11258248.0,lablup,286,6f1c5a2c203da153978b9b334709b33d6ba0383a,a2e85fd58c9d7fe10404bc26f6966f20c9097040,...,Jeongseok Kang,piono623@naver.com,GitHub,noreply@github.com,fix: Update integration test to work with the ...,96.0,55.0,151.0,8.0,"[{'file': 'changes/442.fix.md', 'additions': 1..."
25694,13838497595,70124554,lablup/backend.ai,2904494,kyujin-cho,11258248.0,lablup,1,437e4625f172057e645465c7084492cfeb0143e8,8e26fd42b6ec476b084f237b3b7a4a5c2f8e0c8f,...,Kyujin Cho,kyujin.cho@lablup.com,GitHub,noreply@github.com,feat: update POST `/service` API to also accep...,85.0,38.0,123.0,3.0,[{'file': 'src/ai/backend/client/cli/service.p...
25695,10610526310,70124554,lablup/backend.ai,555156,achimnol,11258248.0,lablup,1,37c8df3174c768b96f542e6511f33ffad219079e,b1c7115142f78f43743f85f417f1f7c852116dc5,...,None,None,None,None,None,NaN,NaN,NaN,NaN,None
25696,10753912953,70124554,lablup/backend.ai,555156,achimnol,11258248.0,lablup,1,6eb9396d72c19b8388a1dec5f9749192f59c1f97,cc5fc1d3b750ad1cae16d18d01544efcc2453caf,...,None,None,None,None,None,NaN,NaN,NaN,NaN,None
25697,7746036447,70124554,lablup/backend.ai,2904494,kyujin-cho,11258248.0,lablup,1,336e17934b58c1d2ad66c29ce5510b10f301431f,5978f16afc6aefafe385b95d2fc48d0d10ce718a,...,None,None,None,None,None,NaN,NaN,NaN,NaN,None

In [418]:
df_repos

                     github repo  count
0             dagster-io/dagster  43538
1     Azure/azure-sdk-for-python  30160
2            DataDog/dd-trace-py  26048
3                  pulumi/pulumi  21919
4                ray-project/ray  20780
...                          ...    ...
5846              hellock/cvbase      1
5847            heroku/heroku.py      1
5848      DenisCarriere/geocoder      1
5849            nickoala/telepot      1
5850    markfinger/python-nodejs      1

[5851 rows x 2 columns]

In [417]:
df_repos = pd.DataFrame(df_push[['repo_name']].value_counts()).reset_index().rename(
    {'repo_name': 'github repo'}, axis = 1)
df_repos.to_csv('data/inputs/github_repo_grab_commits.csv')

In [430]:
import subprocess
lib = 'dagster-io/dagster.git'
lib_p2 = lib.split("/")[1]
lib_ren = lib.replace("/","___")
subprocess.Popen(["git", "clone", f"https://github.com/{lib}", f"{lib_ren}"], cwd = "../repos").wait()

Cloning into 'dagster-io___dagster.git'...
Updating files: 100% (7050/7050), done.

0